package provision.util;

public interface CommonConstants {

	
	int BIS_SOURCE_PIN = 1;
	int BIS_SOURCE_SIM = 2;
	int BIS_SOURCE_ANY = 3;
	int BIS_SOURCE_NONE = 0;
	int BIS_SOURCE_UNKNOWN = -1;
	
	String AUTHENTICATION = "AUTHENTICATION";
	String SIM_SWAP = "SIM_SWAP";
	String PIN_SWAP = "PIN_SWAP";
	String REGIONAL_SIM_SWAP = "REGIONAL_SIM_SWAP";
	String PIN_SIM_SWAP = "PIN_SIM_SWAP";
	String CREATE_BBID = "CREATE_BBID";
	String LOCKED_DEVICE = "LOCKED_DEVICE";
	String SUBSCRIBER_AUTH_SYNC = "SUBSCRIBER_AUTH_SYNC";

	/* To be used with PIN/SIM SWAP handling */
	int NO_SUBSCRIBERS = 0;
	int DEVICE_HAS_SUBSCRIBER = 1;
	int DEVICE_USER = DEVICE_HAS_SUBSCRIBER;
	int SIM_HAS_SUBSCRIBER = 2;
	int SIM_USER = SIM_HAS_SUBSCRIBER;
	int DEVICE_AND_SIM_HAS_AUTH_SUBSCRIBER = 3;  //Note the user of numbers: Both = device + sim
	int DEVICE_OR_SIM_USER = DEVICE_AND_SIM_HAS_AUTH_SUBSCRIBER;
	int NEW_SUBSCRIBER = 4;
	int SUBSCRIBER_CHANGE = 5;
	int DEVICE_HAS_AUTH_SUBSCRIBER = 6;

}
